import pandas as pd
import numpy as np
import os
from utils.constants import (
    RON_TO_EURO_EXCHANGE_MULTIPLIER,
    REDUCED_TVA_MULTIPLIER,
    STANDARD_TVA_MULTIPLIER,
    TVA_THRESHOLD,
    CURRENT_YEAR,
)

pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)

# ==========================================
# 1. TRANSFORMATION FUNCTIONS
# ==========================================


def remove_duplicates(df: pd.DataFrame) -> pd.DataFrame:
    """Removes duplicates generated by scraping redirects and drops ID and url columns."""
    cols_to_check = [col for col in df.columns if col not in ['url', 'listing_id']]
    df = df.drop_duplicates(subset=cols_to_check, keep='first')
    df.drop(columns=["listing_id", "url"], inplace=True)
    return df


def standardize_financials(df: pd.DataFrame) -> pd.DataFrame:
    """Converts currencies, applies VAT, and removes price anomalies."""
    # Drop rows with missing price
    df.dropna(subset="price", inplace=True)

    # Drop obvious bottom outliers
    df = df[df["price"] > 15000]

    # Convert RON to EURO
    ron_mask = df["currency"] == "ron"
    df.loc[ron_mask, "price"] = df.loc[ron_mask, "price"] * RON_TO_EURO_EXCHANGE_MULTIPLIER
    df.loc[ron_mask, "currency"] = "euro"

    # Apply TVA
    mask_reduced_tva = (df["tva_included"] == False) & (df["price"] <= TVA_THRESHOLD)
    mask_standard_tva = (df["tva_included"] == False) & (df["price"] > TVA_THRESHOLD)

    df.loc[mask_reduced_tva, "price"] *= REDUCED_TVA_MULTIPLIER
    df.loc[mask_reduced_tva, "tva_included"] = True

    df.loc[mask_standard_tva, "price"] *= STANDARD_TVA_MULTIPLIER
    df.loc[mask_standard_tva, "tva_included"] = True

    # Final price bounds
    df = df[df["price"] >= 30000]
    df = df[df["price"] <= 750000]

    return df


def clean_spatial_features(df: pd.DataFrame) -> pd.DataFrame:
    """Cleans sectors, handles floor data, and imputes distance to subway."""
    # Clean sector info
    # Mapped Ultracentral to 0
    df['sector'] = df['sector'].replace({'Ultracentral': '0'})
    df['sector'] = pd.to_numeric(df['sector'], errors='coerce')
    df.dropna(subset=['sector'], inplace=True)
    df['sector'] = df['sector'].astype(int).astype(str)

    # Map non-numeric floor values
    floor_mapping = {
        'Parter': 0,
        'Demisol': -1,
        'Subsol': -2,
    }
    df['floor'] = df['floor'].replace(floor_mapping)

    # Temporary numerical column for floor
    df['floor_numeric'] = pd.to_numeric(df['floor'], errors='coerce')

    # Remove broken "Mansardă" rows with no max_floor
    mask_broken_mansarda = (df['floor'] == 'Mansardă') & (df['max_floor'].isna())
    df = df[~mask_broken_mansarda].copy()

    # Set numerical floor for special floor types
    df.loc[df['floor'] == 'Mansardă', 'floor_numeric'] = df['max_floor']
    df.loc[df['floor'] == 'Ultimele2etaje', 'floor_numeric'] = df['max_floor'] - 1

    # Overwrite floor with numeric values
    df['floor'] = df['floor_numeric']
    df.drop(columns=['floor_numeric'], inplace=True)

    # Fill missing max_floor by sector median, then global median
    df["max_floor"] = df["max_floor"].fillna(
        df.groupby("sector")["max_floor"].transform("median")
    )
    df["max_floor"] = df["max_floor"].fillna(df["max_floor"].median())

    # Ensure floor does not exceed max_floor
    df["max_floor"] = df[["floor", "max_floor"]].max(axis=1)

    # Fill floor NaN where max_floor was just imputed
    df.loc[df['floor'].isna() & (df['max_floor'].notna()), 'floor'] = df['max_floor']

    # Create floor_ratio column
    df["floor_ratio"] = df["floor"] / df["max_floor"]
    df["floor_ratio"] = df["floor_ratio"].fillna(0).replace([np.inf, -np.inf], 1)

    # Approximate missing distances to subway (original values were capped at 2000)
    df["distance_to_subway_meters"] = df["distance_to_subway_meters"].fillna(3500)

    return df


def impute_missing_values(df: pd.DataFrame) -> pd.DataFrame:
    """Applies business rules to impute missing values."""
    # Drop rows with missing usable surface
    df.dropna(subset="usable_surface_sq_meters", inplace=True)

    # Handle number_of_bathrooms
    df = df[df["number_of_bathrooms"] <= 6]
    df["number_of_bathrooms"] = df["number_of_bathrooms"].fillna(
        df.groupby("nr_of_rooms")["number_of_bathrooms"].transform("median")
    )
    df["number_of_bathrooms"] = df["number_of_bathrooms"].fillna(1)

    # Handle number of parking spots
    df["parking_spots"] = df["parking_spots"].fillna(0)
    df.loc[df["parking_spots"] > 8, "parking_spots"] = 8

    # Handle missing construction years
    df["construction year"] = df["construction year"].fillna(
        df.groupby("sector")["construction year"].transform("median")
    )
    df["construction year"] = df["construction year"].fillna(
        df["construction year"].median()
    )

    # Create construction_age column
    df["construction_age"] = CURRENT_YEAR - df["construction year"]

    # Handle unknown categorical variables
    df["construction_status"] = df["construction_status"].fillna("Unknown")
    df["layout"] = df["layout"].fillna("Unknown")
    df["comfort_grade"] = df["comfort_grade"].fillna("Unknown")
    df['heating_type'] = df['heating_type'].fillna('Unknown')

    # Filter realistic surfaces (apartments only)
    df = df[(df['usable_surface_sq_meters'] >= 15) & (df['usable_surface_sq_meters'] <= 350)]

    # Filter logical building ages (allow projects finishing in max 3 years)
    df = df[(df['construction_age'] >= -3) & (df['construction_age'] <= 125)]

    return df


def encode_categorical_features(df: pd.DataFrame) -> pd.DataFrame:
    """Prepares data for the model via one-hot encoding."""
    # Drop columns that are no longer needed
    # Too many neighbourhood values to one-hot encode. Sector brings enough information.
    columns_to_drop = [
        'currency', 'tva_included',
        'neighbourhood', 'construction year',
    ]
    df.drop(columns=columns_to_drop, errors='ignore', inplace=True)

    # Ensure sector is string type for one-hot encoding
    df['sector'] = df['sector'].astype(str)

    # One-hot encode categorical values
    categorical_cols = ['layout', 'comfort_grade', 'sector', 'construction_status', 'heating_type']
    df = pd.get_dummies(df, columns=categorical_cols)

    return df


# ==========================================
# 2. MAIN FUNCTION 
# ==========================================


def run_cleaning_pipeline(input_path: str, output_path: str):
    """Runs the entire cleaning ETL process."""
    print(f"Loading data from: {input_path}...")
    df = pd.read_csv(input_path)

    # Transformation chain (highly readable!)
    df = remove_duplicates(df)
    df = standardize_financials(df)
    df = clean_spatial_features(df)
    df = impute_missing_values(df)
    df = encode_categorical_features(df)

    # Save
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    print(f"Saving cleaned data to: {output_path}...")
    df.to_csv(output_path, index=False)
    print("Cleaning completed successfully!")


# ==========================================
# 3. ENTRY POINT
# ==========================================

if __name__ == "__main__":
    INPUT_FILE = "data/raw/raw_listings.csv"
    OUTPUT_FILE = "data/processed/cleaned_listings.csv"

    run_cleaning_pipeline(INPUT_FILE, OUTPUT_FILE)